import { 
  User, 
  SchoolClass, 
  Student, 
  AttendanceSession, 
  AcademicSubject, 
  StudentAcademicGrade, 
  MorningDelayRecord, 
  SchoolAbsenceRecord, 
  StudentObservation, 
  StudentNurturingDossier, 
  CoachGrowthEvaluation, 
  TeacherEvaluation, 
  SchoolAnnouncement, 
  BellPeriod,
  SchoolSettings,
  SchoolGradeItem
} from '../types';

export const INITIAL_SCHOOL_SETTINGS: SchoolSettings = {
  schoolName: 'دبیرستان دوره اول یاوران ولایت',
  phone: '۰۲۱-۸۸۷۷۶۶۵۵',
  address: 'تهران، میدان انقلاب، خیابان فخر رازی، پلاک ۱۱۰',
  academicYear: '۱۴۰۴-۱۴۰۵',
  schoolCode: '۹۶۰۲۱۴۸۸',
  principalName: 'دکتر صادقی',
};

export const INITIAL_SCHOOL_GRADES: SchoolGradeItem[] = [
  { id: 'grd-7', name: 'پایه هفتم', stage: 'دوره اول متوسطه', status: 'active' },
  { id: 'grd-8', name: 'پایه هشتم', stage: 'دوره اول متوسطه', status: 'active' },
  { id: 'grd-9', name: 'پایه نهم', stage: 'دوره اول متوسطه', status: 'active' },
];

export const INITIAL_BELL_PERIODS: BellPeriod[] = [
  {
    id: 'bell-1',
    name: 'زنگ اول',
    startTime: '07:45',
    endTime: '09:15',
    order: 1,
    description: 'نوبت اول صبحگاهی (آموزش دروس پایه و تخصصی)',
  },
  {
    id: 'bell-2',
    name: 'زنگ دوم',
    startTime: '09:30',
    endTime: '11:00',
    order: 2,
    description: 'نوبت دوم صبحگاهی (پس از استراحت اول)',
  },
  {
    id: 'bell-3',
    name: 'زنگ سوم',
    startTime: '11:15',
    endTime: '12:45',
    order: 3,
    description: 'نوبت سوم (پیش از فریضه نماز و ناهار)',
  },
  {
    id: 'bell-4',
    name: 'زنگ چهارم',
    startTime: '13:00',
    endTime: '14:15',
    order: 4,
    description: 'نوبت چهارم (مهارتی، پژوهش، کارگاه و پرورشی)',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    username: 'admin',
    password: '123',
    name: 'دکتر صادقی',
    role: 'admin',
    roleTitle: 'مدیر دبیرستان',
    phone: '09121112233',
    assignedClassIds: ['cls-101', 'cls-102', 'cls-201', 'cls-301'],
  },
  {
    id: 'usr-vp-edu-1',
    username: 'edu_kazemi',
    password: '123',
    name: 'مهندس کاظمی',
    role: 'vice_educational',
    roleTitle: 'معاون آموزشی',
    phone: '09122223344',
    assignedClassIds: ['cls-101', 'cls-102', 'cls-201', 'cls-301'],
  },
  {
    id: 'usr-vp-disc-1',
    username: 'disc_taghavi',
    password: '123',
    name: 'استاد تقوی',
    role: 'vice_disciplinary',
    roleTitle: 'معاون انضباطی',
    phone: '09129998877',
    assignedClassIds: ['cls-101', 'cls-102', 'cls-201', 'cls-301'],
  },
  {
    id: 'usr-vp-nurture-1',
    username: 'nurture_falesiri',
    password: '123',
    name: 'استاد فال اسیری',
    role: 'vice_nurturing',
    roleTitle: 'معاون تربیتی و پرورشی',
    phone: '09127776655',
    assignedClassIds: ['cls-101', 'cls-102', 'cls-201', 'cls-301'],
  },
  {
    id: 'usr-coach-1',
    username: 'coach_mehdipour',
    password: '123',
    name: 'حجت‌الاسلام مهدی‌پور',
    role: 'coach',
    roleTitle: 'مربی پایه دهم (یاوران ولایت)',
    phone: '09123330011',
    assignedClassIds: ['cls-101', 'cls-102'],
  },
  {
    id: 'usr-coach-2',
    username: 'coach_ahmadi',
    password: '123',
    name: 'استاد علیرضا احمدی',
    role: 'coach',
    roleTitle: 'مربی پایه یازدهم و دوازدهم (یاوران ولایت)',
    phone: '09123330022',
    assignedClassIds: ['cls-201', 'cls-301'],
    isAlsoTeacher: true,
    teachingSubject: 'ریاضی',
    teachingClassIds: ['cls-101', 'cls-102'],
    teachingAssignments: [
      {
        id: 'ta-ahmadi-math',
        subjectId: 'sub-1',
        subjectName: 'ریاضی',
        classIds: ['cls-101', 'cls-102'],
      },
    ],
  },
  {
    id: 'usr-tea-1',
    username: 'rezaei',
    password: '123',
    name: 'استاد احمد رضایی',
    role: 'teacher',
    roleTitle: 'دبیر علوم تجربی',
    subject: 'علوم تجربی',
    phone: '09123334455',
    assignedClassIds: ['cls-101', 'cls-102', 'cls-201'],
  },
  {
    id: 'usr-tea-2',
    username: 'hosseini',
    password: '123',
    name: 'استاد حسین حسینی',
    role: 'teacher',
    roleTitle: 'دبیر ریاضی',
    subject: 'ریاضی',
    phone: '09124445566',
    assignedClassIds: ['cls-101', 'cls-102', 'cls-301'],
  },
  {
    id: 'usr-tea-3',
    username: 'karimi',
    password: '123',
    name: 'استاد مریم کریمی',
    role: 'teacher',
    roleTitle: 'دبیر زبان انگلیسی',
    subject: 'زبان انگلیسی',
    phone: '09125556677',
    assignedClassIds: ['cls-101', 'cls-102', 'cls-301'],
  },
  {
    id: 'usr-tea-4',
    username: 'mahdavi',
    password: '123',
    name: 'استاد علی مهدوی',
    role: 'teacher',
    roleTitle: 'دبیر مطالعات اجتماعی',
    subject: 'مطالعات اجتماعی',
    phone: '09126667788',
    assignedClassIds: ['cls-101', 'cls-102', 'cls-201'],
  },
  {
    id: 'usr-tea-5',
    username: 'karimian',
    password: '123',
    name: 'استاد علیرضا کریمیان',
    role: 'teacher',
    roleTitle: 'دبیر ادبیات فارسی و نگارش',
    subject: 'فارسی و نگارش',
    phone: '09127778899',
    assignedClassIds: ['cls-101', 'cls-201', 'cls-301'],
  },
  {
    id: 'usr-tea-6',
    username: 'alavi',
    password: '123',
    name: 'استاد محسن علوی',
    role: 'teacher',
    roleTitle: 'دبیر پیام‌های آسمان و قرآن',
    subject: 'پیام‌های آسمان و قرآن',
    phone: '09128889900',
    assignedClassIds: ['cls-101', 'cls-102', 'cls-201', 'cls-301'],
  },
  {
    id: 'usr-tea-7',
    username: 'mousavi',
    password: '123',
    name: 'استاد سید مهدی موسوی',
    role: 'teacher',
    roleTitle: 'دبیر زبان عربی',
    subject: 'عربی',
    phone: '09129990011',
    assignedClassIds: ['cls-101', 'cls-102', 'cls-201', 'cls-301'],
  },
  {
    id: 'usr-tea-8',
    username: 'akbari',
    password: '123',
    name: 'استاد مسعود اکبری',
    role: 'teacher',
    roleTitle: 'دبیر کار و فناوری و تفکر',
    subject: 'کار و فناوری و تفکر',
    phone: '09121113344',
    assignedClassIds: ['cls-101', 'cls-201'],
  },
  {
    id: 'usr-tea-9',
    username: 'radmanesh',
    password: '123',
    name: 'استاد بهرام رادمنش',
    role: 'teacher',
    roleTitle: 'دبیر فرهنگ و هنر و تربیت بدنی',
    subject: 'فرهنگ و هنر و تربیت بدنی',
    phone: '09122224455',
    assignedClassIds: ['cls-101', 'cls-102', 'cls-201', 'cls-301'],
  },
];

export const INITIAL_CLASSES: SchoolClass[] = [
  {
    id: 'cls-101',
    name: 'هفتم ۱ (کلاس ۱۰۱)',
    grade: 'پایه هفتم',
    major: 'متوسطه اول',
    academicYear: '۱۴۰۴-۱۴۰۵',
    roomNumber: '۱۰۱',
    teacherIds: ['usr-tea-1', 'usr-tea-2', 'usr-tea-3', 'usr-tea-4', 'usr-tea-5', 'usr-tea-6', 'usr-coach-2'],
    coachId: 'usr-coach-1',
    defaultStartTime: '07:45',
    defaultEndTime: '09:15',
    defaultBellPeriodId: 'bell-1',
  },
  {
    id: 'cls-102',
    name: 'هفتم ۲ (کلاس ۱۰۲)',
    grade: 'پایه هفتم',
    major: 'متوسطه اول',
    academicYear: '۱۴۰۴-۱۴۰۵',
    roomNumber: '۱۰۲',
    teacherIds: ['usr-tea-1', 'usr-tea-2', 'usr-tea-3', 'usr-tea-6', 'usr-tea-7', 'usr-coach-2'],
    coachId: 'usr-coach-1',
    defaultStartTime: '07:45',
    defaultEndTime: '09:15',
    defaultBellPeriodId: 'bell-1',
  },
  {
    id: 'cls-201',
    name: 'هشتم ۱ (کلاس ۲۰۱)',
    grade: 'پایه هشتم',
    major: 'متوسطه اول',
    academicYear: '۱۴۰۴-۱۴۰۵',
    roomNumber: '۲۰۱',
    teacherIds: ['usr-tea-1', 'usr-tea-2', 'usr-tea-4', 'usr-tea-5', 'usr-tea-8'],
    coachId: 'usr-coach-2',
    defaultStartTime: '07:45',
    defaultEndTime: '09:15',
    defaultBellPeriodId: 'bell-1',
  },
  {
    id: 'cls-301',
    name: 'نهم ۱ (کلاس ۳۰۱)',
    grade: 'پایه نهم',
    major: 'متوسطه اول',
    academicYear: '۱۴۰۴-۱۴۰۵',
    roomNumber: '۳۰۱',
    teacherIds: ['usr-tea-2', 'usr-tea-3', 'usr-tea-5', 'usr-tea-6', 'usr-tea-9'],
    coachId: 'usr-coach-2',
    defaultStartTime: '07:45',
    defaultEndTime: '09:15',
    defaultBellPeriodId: 'bell-1',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  // Class 101 Students
  {
    id: 'stu-101-1',
    classId: 'cls-101',
    studentCode: '40410101',
    nationalId: '0021456781',
    firstName: 'امیرحسین',
    lastName: 'محمدی',
    fatherName: 'محسن',
    parentPhone: '09123450001',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
    disciplinaryNotes: [],
  },
  {
    id: 'stu-101-2',
    classId: 'cls-101',
    studentCode: '40410102',
    nationalId: '0021456782',
    firstName: 'علی‌رضا',
    lastName: 'احمدی',
    fatherName: 'حسین',
    parentPhone: '09123450002',
    disciplineScore: 19.5,
    disciplinaryStatus: 'normal',
    disciplinaryNotes: [
      {
        id: 'dn-1',
        date: '1404/08/12',
        title: 'تاخیر در ورود به کلاس',
        description: '۱۰ دقیقه تاخیر در زنگ اول',
        scoreDeduction: 0.5,
        recordedBy: 'معاون انضباطی',
        type: 'delay',
      }
    ],
  },
  {
    id: 'stu-101-3',
    classId: 'cls-101',
    studentCode: '40410103',
    nationalId: '0021456783',
    firstName: 'سهراب',
    lastName: 'سپهری',
    fatherName: 'منوچهر',
    parentPhone: '09123450003',
    disciplineScore: 17,
    disciplinaryStatus: 'written_warning',
    disciplinaryNotes: [
      {
        id: 'dn-2',
        date: '1404/08/10',
        title: 'غیبت غیرموجه',
        description: 'غیبت بدون هماهنگی و عذر موجه در زنگ فیزیک',
        scoreDeduction: 1.5,
        recordedBy: 'معاون انضباطی',
        type: 'absence',
      },
      {
        id: 'dn-3',
        date: '1404/08/17',
        title: 'اخطار کتبی غیبت مکرر',
        description: 'صدور اخطار کتبی و اطلاع‌رسانی به ولی دانش‌آموز',
        scoreDeduction: 1.5,
        recordedBy: 'معاون انضباطی',
        type: 'absence',
      }
    ],
  },
  {
    id: 'stu-101-4',
    classId: 'cls-101',
    studentCode: '40410104',
    nationalId: '0021456784',
    firstName: 'محمدمهدی',
    lastName: 'کریمیان',
    fatherName: 'مرتضی',
    parentPhone: '09123450004',
    disciplineScore: 19.5,
    disciplinaryStatus: 'verbal_warning',
    disciplinaryNotes: [
      {
        id: 'dn-4',
        date: '1404/08/10',
        title: 'تاخیر صبحگاهی',
        description: '۱۵ دقیقه تاخیر در ورود به مدرسه',
        scoreDeduction: 0.5,
        recordedBy: 'معاون انضباطی',
        type: 'delay',
      }
    ],
  },
  {
    id: 'stu-101-5',
    classId: 'cls-101',
    studentCode: '40410105',
    nationalId: '0021456785',
    firstName: 'پویا',
    lastName: 'رحمانی',
    fatherName: 'داوود',
    parentPhone: '09123450005',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
    disciplinaryNotes: [],
  },
  {
    id: 'stu-101-6',
    classId: 'cls-101',
    studentCode: '40410106',
    nationalId: '0021456786',
    firstName: 'آرش',
    lastName: 'نیک‌پور',
    fatherName: 'بهروز',
    parentPhone: '09123450006',
    disciplineScore: 18.5,
    disciplinaryStatus: 'verbal_warning',
    disciplinaryNotes: [
      {
        id: 'dn-5',
        date: '1404/08/17',
        title: 'تاخیر در کلاس و نقص تکلیف',
        description: '۲۰ دقیقه تاخیر در کلاس فیزیک',
        scoreDeduction: 1.5,
        recordedBy: 'معاون انضباطی',
        type: 'delay',
      }
    ],
  },
  {
    id: 'stu-101-7',
    classId: 'cls-101',
    studentCode: '40410107',
    nationalId: '0021456787',
    firstName: 'کیان',
    lastName: 'شجاعی',
    fatherName: 'فرهاد',
    parentPhone: '09123450007',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
    disciplinaryNotes: [],
  },
  {
    id: 'stu-101-8',
    classId: 'cls-101',
    studentCode: '40410108',
    nationalId: '0021456788',
    firstName: 'بردیا',
    lastName: 'صادق‌پور',
    fatherName: 'سعید',
    parentPhone: '09123450008',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
    disciplinaryNotes: [],
  },

  // Class 102 Students
  {
    id: 'stu-102-1',
    classId: 'cls-102',
    studentCode: '40410201',
    nationalId: '0022456701',
    firstName: 'فرهاد',
    lastName: 'مهرابی',
    fatherName: 'جواد',
    parentPhone: '09123460001',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
  },
  {
    id: 'stu-102-2',
    classId: 'cls-102',
    studentCode: '40410202',
    nationalId: '0022456702',
    firstName: 'دانیال',
    lastName: 'حکیمی',
    fatherName: 'عباس',
    parentPhone: '09123460002',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
  },
  {
    id: 'stu-102-3',
    classId: 'cls-102',
    studentCode: '40410203',
    nationalId: '0022456703',
    firstName: 'امید',
    lastName: 'قاسمی',
    fatherName: 'قاسم',
    parentPhone: '09123460003',
    disciplineScore: 19,
    disciplinaryStatus: 'verbal_warning',
    disciplinaryNotes: [
      {
        id: 'dn-6',
        date: '1404/08/11',
        title: 'تاخیر در زنگ شیمی',
        description: '۱۵ دقیقه تاخیر',
        scoreDeduction: 1,
        recordedBy: 'معاون انضباطی',
        type: 'delay',
      }
    ],
  },
  {
    id: 'stu-102-4',
    classId: 'cls-102',
    studentCode: '40410204',
    nationalId: '0022456704',
    firstName: 'عرفان',
    lastName: 'جعفری',
    fatherName: 'علیرضا',
    parentPhone: '09123460004',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
  },
  {
    id: 'stu-102-5',
    classId: 'cls-102',
    studentCode: '40410205',
    nationalId: '0022456705',
    firstName: 'پرهام',
    lastName: 'یوسفی',
    fatherName: 'محمد',
    parentPhone: '09123460005',
    disciplineScore: 18.5,
    disciplinaryStatus: 'verbal_warning',
    disciplinaryNotes: [
      {
        id: 'dn-7',
        date: '1404/08/11',
        title: 'غیبت غیرموجه',
        description: 'غیبت غیرموجه در زنگ دوم',
        scoreDeduction: 1.5,
        recordedBy: 'معاون انضباطی',
        type: 'absence',
      }
    ],
  },

  // Class 201 Students
  {
    id: 'stu-201-1',
    classId: 'cls-201',
    studentCode: '40420101',
    nationalId: '0023456701',
    firstName: 'متین',
    lastName: 'روستایی',
    fatherName: 'اکبر',
    parentPhone: '09123470001',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
  },
  {
    id: 'stu-201-2',
    classId: 'cls-201',
    studentCode: '40420102',
    nationalId: '0023456702',
    firstName: 'شایان',
    lastName: 'طباطبایی',
    fatherName: 'مهدی',
    parentPhone: '09123470002',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
  },
  {
    id: 'stu-201-3',
    classId: 'cls-201',
    studentCode: '40420103',
    nationalId: '0023456703',
    firstName: 'نیما',
    lastName: 'کاظمیان',
    fatherName: 'هادی',
    parentPhone: '09123470003',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
  },

  // Class 301 Students
  {
    id: 'stu-301-1',
    classId: 'cls-301',
    studentCode: '40430101',
    nationalId: '0024456701',
    firstName: 'سینا',
    lastName: 'فروغی',
    fatherName: 'کامبیز',
    parentPhone: '09123480001',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
  },
  {
    id: 'stu-301-2',
    classId: 'cls-301',
    studentCode: '40430102',
    nationalId: '0024456702',
    firstName: 'یاشار',
    lastName: 'افشار',
    fatherName: 'ناصر',
    parentPhone: '09123480002',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
  },
  {
    id: 'stu-301-3',
    classId: 'cls-301',
    studentCode: '40430103',
    nationalId: '0024456703',
    firstName: 'ماهان',
    lastName: 'موسوی',
    fatherName: 'سید علی',
    parentPhone: '09123480003',
    disciplineScore: 20,
    disciplinaryStatus: 'normal',
  },
];

export const INITIAL_SESSIONS: AttendanceSession[] = [
  {
    id: 'ses-101-1',
    classId: 'cls-101',
    teacherId: 'usr-tea-1',
    teacherName: 'استاد احمد رضایی',
    subject: 'فیزیک ۱',
    date: '1404/08/10',
    dayOfWeek: 'شنبه',
    startTime: '08:00',
    endTime: '09:30',
    lessonTopic: 'فصل ۲: کار، انرژی و توان - قضیه کار و انرژی جنبشی',
    homeworkDescription: 'حل تمرین‌های انتهای فصل صفحه ۴۲ تا ۴۵ کتاب درسی',
    sessionNotes: 'حل ۵ مثال متنوع از قضیه کار و انرژی - پرسش شفاهی از دانش‌آموزان',
    records: {
      'stu-101-1': { studentId: 'stu-101-1', status: 'present', score: 19, homeworkStatus: 'done' },
      'stu-101-2': { studentId: 'stu-101-2', status: 'present', score: 18, homeworkStatus: 'done' },
      'stu-101-3': { studentId: 'stu-101-3', status: 'absent', note: 'غیبت غیرموجه بدون اطلاع اولیا' },
      'stu-101-4': { studentId: 'stu-101-4', status: 'late', delayMinutes: 15, homeworkStatus: 'done' },
      'stu-101-5': { studentId: 'stu-101-5', status: 'present', score: 20, homeworkStatus: 'done' },
      'stu-101-6': { studentId: 'stu-101-6', status: 'present', score: 17, homeworkStatus: 'incomplete' },
      'stu-101-7': { studentId: 'stu-101-7', status: 'excused', note: 'گواهی پزشکی ارائه شد' },
      'stu-101-8': { studentId: 'stu-101-8', status: 'present', score: 18, homeworkStatus: 'done' },
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ses-101-2',
    classId: 'cls-101',
    teacherId: 'usr-tea-2',
    teacherName: 'استاد حسین حسینی',
    subject: 'ریاضی ۱',
    date: '1404/08/12',
    dayOfWeek: 'دوشنبه',
    startTime: '09:45',
    endTime: '11:15',
    lessonTopic: 'اتحادها و عبارتهای جبری - روش‌های تجزیه چندجمله‌ای‌ها',
    homeworkDescription: 'حل مسایل آزمونک ۱ و تمرین صفحه ۵۸',
    sessionNotes: 'کوئیز کلاسی ۱۰ دقیقه‌ای برگزار شد',
    records: {
      'stu-101-1': { studentId: 'stu-101-1', status: 'present', score: 20, homeworkStatus: 'done' },
      'stu-101-2': { studentId: 'stu-101-2', status: 'late', delayMinutes: 10, homeworkStatus: 'done' },
      'stu-101-3': { studentId: 'stu-101-3', status: 'absent', note: 'دومین جلسه غیبت' },
      'stu-101-4': { studentId: 'stu-101-4', status: 'present', score: 16, homeworkStatus: 'done' },
      'stu-101-5': { studentId: 'stu-101-5', status: 'present', score: 19, homeworkStatus: 'done' },
      'stu-101-6': { studentId: 'stu-101-6', status: 'present', score: 15, homeworkStatus: 'done' },
      'stu-101-7': { studentId: 'stu-101-7', status: 'present', score: 18, homeworkStatus: 'done' },
      'stu-101-8': { studentId: 'stu-101-8', status: 'present', score: 17, homeworkStatus: 'done' },
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ses-101-3',
    classId: 'cls-101',
    teacherId: 'usr-tea-1',
    teacherName: 'استاد احمد رضایی',
    subject: 'فیزیک ۱',
    date: '1404/08/17',
    dayOfWeek: 'شنبه',
    startTime: '08:00',
    endTime: '09:30',
    lessonTopic: 'پایستگی انرژی مکانیکی و بررسی اصطکاک',
    homeworkDescription: 'تکلیف آنلاین سامانه حل شود',
    sessionNotes: 'مشارکت کلاسی بسیار خوب بود',
    records: {
      'stu-101-1': { studentId: 'stu-101-1', status: 'present', score: 19, homeworkStatus: 'done' },
      'stu-101-2': { studentId: 'stu-101-2', status: 'present', score: 17, homeworkStatus: 'done' },
      'stu-101-3': { studentId: 'stu-101-3', status: 'absent', note: 'غیبت مکرر - نیازمند اخطار' },
      'stu-101-4': { studentId: 'stu-101-4', status: 'present', score: 18, homeworkStatus: 'done' },
      'stu-101-5': { studentId: 'stu-101-5', status: 'present', score: 20, homeworkStatus: 'done' },
      'stu-101-6': { studentId: 'stu-101-6', status: 'late', delayMinutes: 20, homeworkStatus: 'not_done' },
      'stu-101-7': { studentId: 'stu-101-7', status: 'present', score: 19, homeworkStatus: 'done' },
      'stu-101-8': { studentId: 'stu-101-8', status: 'present', score: 18, homeworkStatus: 'done' },
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ses-102-1',
    classId: 'cls-102',
    teacherId: 'usr-tea-3',
    teacherName: 'استاد مریم کریمی',
    subject: 'شیمی ۱',
    date: '1404/08/11',
    dayOfWeek: 'یکشنبه',
    startTime: '10:00',
    endTime: '11:30',
    lessonTopic: 'آرایش الکترونی عناصر و جدول تناوبی',
    homeworkDescription: 'رسم آرایش الکترونی عناصر دوره ۳ و ۴',
    sessionNotes: 'حل تست‌های کنکور سراسری',
    records: {
      'stu-102-1': { studentId: 'stu-102-1', status: 'present', score: 19, homeworkStatus: 'done' },
      'stu-102-2': { studentId: 'stu-102-2', status: 'present', score: 18, homeworkStatus: 'done' },
      'stu-102-3': { studentId: 'stu-102-3', status: 'late', delayMinutes: 15, homeworkStatus: 'done' },
      'stu-102-4': { studentId: 'stu-102-4', status: 'present', score: 17, homeworkStatus: 'done' },
      'stu-102-5': { studentId: 'stu-102-5', status: 'absent', note: 'غیبت غیرموجه' },
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const JUNIOR_HIGH_STANDARD_SUBJECTS: import('../types').AcademicSubject[] = [
  {
    id: 'sub-1',
    code: 'MATH',
    name: 'ریاضی',
    coefficient: 4,
    hoursPerWeek: 4,
    category: 'علوم پایه',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-2',
    defaultTeacherName: 'استاد حسین حسینی',
    description: 'آموزش هندسه، جبر و معادلات، اعداد صحیح و توان و جذر',
  },
  {
    id: 'sub-2',
    code: 'SCI',
    name: 'علوم تجربی',
    coefficient: 3,
    hoursPerWeek: 3,
    category: 'علوم پایه',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-1',
    defaultTeacherName: 'استاد احمد رضایی',
    description: 'فیزیک، شیمی، زیست‌شناسی و زمین‌شناسی پایه متوسطه اول و آزمایشگاه',
  },
  {
    id: 'sub-3',
    code: 'LIT',
    name: 'فارسی (ادبیات فارسی)',
    coefficient: 4,
    hoursPerWeek: 4,
    category: 'ادبیات و معارف',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-5',
    defaultTeacherName: 'استاد علیرضا کریمیان',
    description: 'آرایه‌های ادبی، درک مطلب، دستور زبان فارسی و تاریخ ادبیات',
  },
  {
    id: 'sub-4',
    code: 'WRIT',
    name: 'نگارش و انشا',
    coefficient: 2,
    hoursPerWeek: 2,
    category: 'ادبیات و معارف',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-5',
    defaultTeacherName: 'استاد علیرضا کریمیان',
    description: 'اصول نگارش، سنجش و بازآفرینی متن و مهارت‌های نوشتاری',
  },
  {
    id: 'sub-5',
    code: 'QUR',
    name: 'آموزش قرآن',
    coefficient: 2,
    hoursPerWeek: 2,
    category: 'ادبیات و معارف',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-6',
    defaultTeacherName: 'استاد محسن علوی',
    description: 'روخوانی، روان‌خوانی، مفاهیم قرآنی و درک پیام آیات',
  },
  {
    id: 'sub-6',
    code: 'REL',
    name: 'پیام‌های آسمان (دینی)',
    coefficient: 2,
    hoursPerWeek: 2,
    category: 'ادبیات و معارف',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-6',
    defaultTeacherName: 'استاد محسن علوی',
    description: 'معارف اسلامی، احکام، اخلاق و سیره نبوی و اهل بیت (ع)',
  },
  {
    id: 'sub-7',
    code: 'SOC',
    name: 'مطالعات اجتماعی (تاریخ، جغرافیا، مدنی)',
    coefficient: 3,
    hoursPerWeek: 3,
    category: 'علوم اجتماعی و فرهنگ',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-4',
    defaultTeacherName: 'استاد علی مهدوی',
    description: 'تاریخ ایران و اسلام، جغرافیای عمومی و کشور، حقوق و تکالیف شهروندی',
  },
  {
    id: 'sub-8',
    code: 'ARB',
    name: 'عربی (زبان قرآن)',
    coefficient: 2,
    hoursPerWeek: 2,
    category: 'زبان‌های خارجی',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-7',
    defaultTeacherName: 'استاد سید مهدی موسوی',
    description: 'قواعد عربی، ترجمه و متون کاربردی دوره اول دبیرستان',
  },
  {
    id: 'sub-9',
    code: 'ENG',
    name: 'زبان انگلیسی',
    coefficient: 2,
    hoursPerWeek: 2,
    category: 'زبان‌های خارجی',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-3',
    defaultTeacherName: 'استاد مریم کریمی',
    description: 'مهارت‌های چهارگانه شنیداری، گفتاری، خواندن و نوشتن انگلیسی',
  },
  {
    id: 'sub-10',
    code: 'TECH',
    name: 'کار و فناوری',
    coefficient: 2,
    hoursPerWeek: 2,
    category: 'مهارتی و فناوری',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-8',
    defaultTeacherName: 'استاد مسعود اکبری',
    description: 'مهارت‌های عملی، پودمان‌های کاربردی، فناوری اطلاعات و کارآفرینی',
  },
  {
    id: 'sub-11',
    code: 'ART',
    name: 'فرهنگ و هنر',
    coefficient: 2,
    hoursPerWeek: 2,
    category: 'علوم اجتماعی و فرهنگ',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-9',
    defaultTeacherName: 'استاد بهرام رادمنش',
    description: 'طراحی، خوشنویسی، هنرهای سنتی، عکاسی و سرود',
  },
  {
    id: 'sub-12',
    code: 'THINK',
    name: 'تفکر و سبک زندگی',
    coefficient: 2,
    hoursPerWeek: 2,
    category: 'مهارتی و فناوری',
    grade: 'پایه هفتم و هشتم',
    targetGrades: ['پایه هفتم', 'پایه هشتم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-8',
    defaultTeacherName: 'استاد مسعود اکبری',
    description: 'تفکر نقاد، حل مسئله، مهارت‌های ارتباطی و سبک زندگی اسلامی-ایرانی',
  },
  {
    id: 'sub-13',
    code: 'DEF',
    name: 'آمادگی دفاعی (پایه نهم)',
    coefficient: 2,
    hoursPerWeek: 2,
    category: 'علوم اجتماعی و فرهنگ',
    grade: 'پایه نهم',
    targetGrades: ['پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-9',
    defaultTeacherName: 'استاد بهرام رادمنش',
    description: 'آشنایی با مفاهیم دفاع مقدس، پدافند غیرعامل، امداد و نجات و امنیت ملی',
  },
  {
    id: 'sub-14',
    code: 'PE',
    name: 'تربیت بدنی و سلامت',
    coefficient: 2,
    hoursPerWeek: 2,
    category: 'تربیت بدنی و سلامت',
    grade: 'عمومی متوسطه اول',
    targetGrades: ['پایه هفتم', 'پایه هشتم', 'پایه نهم'],
    major: 'متوسطه اول',
    teacherId: 'usr-tea-9',
    defaultTeacherName: 'استاد بهرام رادمنش',
    description: 'آمادگی جسمانی، مهارت‌های ورزشی توپی، بهداشت فردی و تغذیه سالم',
  },
];

export const INITIAL_ACADEMIC_SUBJECTS: import('../types').AcademicSubject[] = JUNIOR_HIGH_STANDARD_SUBJECTS;

export const INITIAL_ACADEMIC_GRADES: import('../types').StudentAcademicGrade[] = [
  // Student 1: امیرحسین محمدی (cls-101) - Great growth profile
  {
    id: 'grd-101-1-1',
    studentId: 'stu-101-1',
    classId: 'cls-101',
    subjectId: 'sub-1',
    subjectName: 'ریاضی و حسابان',
    coefficient: 4,
    mehrContinuous: 16.5,
    abanContinuous: 17.0,
    azarContinuous: 18.0,
    term1Continuous: 17.5,
    term1Final: 16.0,
    bahmanContinuous: 18.0,
    esfandContinuous: 18.5,
    farvardinContinuous: 19.0,
    ordibeheshtContinuous: 19.5,
    term2Continuous: 18.5,
    term2Final: 19.5,
    teacherName: 'استاد حسین حسینی',
    notes: 'پیشرفت عالی در مباحث مشتق و حد',
  },
  {
    id: 'grd-101-1-2',
    studentId: 'stu-101-1',
    classId: 'cls-101',
    subjectId: 'sub-2',
    subjectName: 'فیزیک',
    coefficient: 3,
    mehrContinuous: 17.0,
    abanContinuous: 18.0,
    azarContinuous: 18.5,
    term1Continuous: 18.0,
    term1Final: 17.5,
    bahmanContinuous: 18.5,
    esfandContinuous: 19.0,
    farvardinContinuous: 19.5,
    ordibeheshtContinuous: 20.0,
    term2Continuous: 19.0,
    term2Final: 20.0,
    teacherName: 'استاد احمد رضایی',
    notes: 'پاسخگویی بی‌نقص در حل مسائل مغناطیس',
  },
  {
    id: 'grd-101-1-3',
    studentId: 'stu-101-1',
    classId: 'cls-101',
    subjectId: 'sub-3',
    subjectName: 'شیمی',
    coefficient: 3,
    mehrContinuous: 15.0,
    abanContinuous: 16.0,
    azarContinuous: 16.5,
    term1Continuous: 16.0,
    term1Final: 15.5,
    bahmanContinuous: 16.5,
    esfandContinuous: 17.0,
    farvardinContinuous: 17.5,
    ordibeheshtContinuous: 18.0,
    term2Continuous: 17.0,
    term2Final: 18.5,
    teacherName: 'استاد مریم کریمی',
    notes: 'رشد چشمگیر پس از کلاس‌های فوق‌برنامه',
  },
  {
    id: 'grd-101-1-4',
    studentId: 'stu-101-1',
    classId: 'cls-101',
    subjectId: 'sub-4',
    subjectName: 'هندسه',
    coefficient: 2,
    mehrContinuous: 14.0,
    abanContinuous: 15.0,
    azarContinuous: 15.5,
    term1Continuous: 15.0,
    term1Final: 14.5,
    bahmanContinuous: 16.0,
    esfandContinuous: 16.5,
    farvardinContinuous: 17.0,
    ordibeheshtContinuous: 17.0,
    term2Continuous: 16.5,
    term2Final: 17.5,
    teacherName: 'استاد حسین حسینی',
  },
  {
    id: 'grd-101-1-5',
    studentId: 'stu-101-1',
    classId: 'cls-101',
    subjectId: 'sub-5',
    subjectName: 'زبان انگلیسی',
    coefficient: 2,
    mehrContinuous: 19.0,
    abanContinuous: 19.0,
    azarContinuous: 19.5,
    term1Continuous: 19.0,
    term1Final: 18.5,
    bahmanContinuous: 19.5,
    esfandContinuous: 19.5,
    farvardinContinuous: 20.0,
    ordibeheshtContinuous: 20.0,
    term2Continuous: 19.5,
    term2Final: 20.0,
    teacherName: 'استاد علی مهدوی',
  },
  {
    id: 'grd-101-1-6',
    studentId: 'stu-101-1',
    classId: 'cls-101',
    subjectId: 'sub-6',
    subjectName: 'ادبیات فارسی و نگارش',
    coefficient: 4,
    mehrContinuous: 18.0,
    abanContinuous: 18.5,
    azarContinuous: 19.0,
    term1Continuous: 18.5,
    term1Final: 18.0,
    bahmanContinuous: 19.0,
    esfandContinuous: 19.0,
    farvardinContinuous: 19.5,
    ordibeheshtContinuous: 19.5,
    term2Continuous: 19.0,
    term2Final: 19.0,
    teacherName: 'استاد کریمیان',
  },

  // Student 2: علی‌رضا احمدی (cls-101) - Solid steady student
  {
    id: 'grd-101-2-1',
    studentId: 'stu-101-2',
    classId: 'cls-101',
    subjectId: 'sub-1',
    subjectName: 'ریاضی و حسابان',
    coefficient: 4,
    mehrContinuous: 15.5,
    abanContinuous: 16.0,
    azarContinuous: 16.5,
    term1Continuous: 16.0,
    term1Final: 15.0,
    bahmanContinuous: 16.5,
    esfandContinuous: 17.0,
    farvardinContinuous: 17.0,
    ordibeheshtContinuous: 17.5,
    term2Continuous: 17.0,
    term2Final: 17.5,
    teacherName: 'استاد حسین حسینی',
  },
  {
    id: 'grd-101-2-2',
    studentId: 'stu-101-2',
    classId: 'cls-101',
    subjectId: 'sub-2',
    subjectName: 'فیزیک',
    coefficient: 3,
    mehrContinuous: 15.0,
    abanContinuous: 15.5,
    azarContinuous: 16.0,
    term1Continuous: 15.5,
    term1Final: 16.0,
    bahmanContinuous: 16.0,
    esfandContinuous: 16.5,
    farvardinContinuous: 17.0,
    ordibeheshtContinuous: 17.0,
    term2Continuous: 16.5,
    term2Final: 17.0,
    teacherName: 'استاد احمد رضایی',
  },
  {
    id: 'grd-101-2-3',
    studentId: 'stu-101-2',
    classId: 'cls-101',
    subjectId: 'sub-3',
    subjectName: 'شیمی',
    coefficient: 3,
    mehrContinuous: 17.5,
    abanContinuous: 18.0,
    azarContinuous: 18.0,
    term1Continuous: 18.0,
    term1Final: 18.5,
    bahmanContinuous: 18.0,
    esfandContinuous: 18.5,
    farvardinContinuous: 19.0,
    ordibeheshtContinuous: 19.0,
    term2Continuous: 18.5,
    term2Final: 19.0,
    teacherName: 'استاد مریم کریمی',
  },
  {
    id: 'grd-101-2-5',
    studentId: 'stu-101-2',
    classId: 'cls-101',
    subjectId: 'sub-5',
    subjectName: 'زبان انگلیسی',
    coefficient: 2,
    mehrContinuous: 16.5,
    abanContinuous: 17.0,
    azarContinuous: 17.0,
    term1Continuous: 17.0,
    term1Final: 16.5,
    bahmanContinuous: 17.0,
    esfandContinuous: 17.5,
    farvardinContinuous: 18.0,
    ordibeheshtContinuous: 18.0,
    term2Continuous: 17.5,
    term2Final: 18.0,
    teacherName: 'استاد علی مهدوی',
  },

  // Student 3: سهراب سپهری (cls-101) - Needs Attention in Math/Physics
  {
    id: 'grd-101-3-1',
    studentId: 'stu-101-3',
    classId: 'cls-101',
    subjectId: 'sub-1',
    subjectName: 'ریاضی و حسابان',
    coefficient: 4,
    mehrContinuous: 13.0,
    abanContinuous: 12.0,
    azarContinuous: 11.5,
    term1Continuous: 12.0,
    term1Final: 10.5,
    bahmanContinuous: 12.5,
    esfandContinuous: 13.0,
    farvardinContinuous: 13.0,
    ordibeheshtContinuous: 13.5,
    term2Continuous: 13.0,
    term2Final: 12.0,
    teacherName: 'استاد حسین حسینی',
    notes: 'نیازمند تمرین بیشتر در جبر و آنالیز',
  },
  {
    id: 'grd-101-3-2',
    studentId: 'stu-101-3',
    classId: 'cls-101',
    subjectId: 'sub-2',
    subjectName: 'فیزیک',
    coefficient: 3,
    mehrContinuous: 12.5,
    abanContinuous: 11.5,
    azarContinuous: 11.0,
    term1Continuous: 11.5,
    term1Final: 9.5,
    bahmanContinuous: 11.5,
    esfandContinuous: 12.0,
    farvardinContinuous: 12.5,
    ordibeheshtContinuous: 12.5,
    term2Continuous: 12.0,
    term2Final: 11.0,
    teacherName: 'استاد احمد رضایی',
    notes: 'همبستگی افت نمره با غیبت‌های مکرر در جلسات',
  },
  {
    id: 'grd-101-3-5',
    studentId: 'stu-101-3',
    classId: 'cls-101',
    subjectId: 'sub-5',
    subjectName: 'زبان انگلیسی',
    coefficient: 2,
    mehrContinuous: 18.0,
    abanContinuous: 18.0,
    azarContinuous: 18.5,
    term1Continuous: 18.0,
    term1Final: 19.0,
    bahmanContinuous: 18.5,
    esfandContinuous: 19.0,
    farvardinContinuous: 19.5,
    ordibeheshtContinuous: 19.5,
    term2Continuous: 19.0,
    term2Final: 19.5,
    teacherName: 'استاد علی مهدوی',
    notes: 'نقطه قوت شاخص دانش‌آموز',
  },
  {
    id: 'grd-101-3-6',
    studentId: 'stu-101-3',
    classId: 'cls-101',
    subjectId: 'sub-6',
    subjectName: 'ادبیات فارسی و نگارش',
    coefficient: 4,
    mehrContinuous: 19.0,
    abanContinuous: 19.5,
    azarContinuous: 20.0,
    term1Continuous: 19.5,
    term1Final: 20.0,
    bahmanContinuous: 20.0,
    esfandContinuous: 20.0,
    farvardinContinuous: 20.0,
    ordibeheshtContinuous: 20.0,
    term2Continuous: 20.0,
    term2Final: 20.0,
    teacherName: 'استاد کریمیان',
    notes: 'استعداد درخشان در انشا و تحلیل متون ادبی',
  },

  // Student 4: محمدمهدی کریمیان (cls-101)
  {
    id: 'grd-101-4-1',
    studentId: 'stu-101-4',
    classId: 'cls-101',
    subjectId: 'sub-1',
    subjectName: 'ریاضی و حسابان',
    coefficient: 4,
    mehrContinuous: 18.5,
    abanContinuous: 19.0,
    azarContinuous: 19.0,
    term1Continuous: 19.0,
    term1Final: 18.5,
    bahmanContinuous: 19.0,
    esfandContinuous: 19.5,
    farvardinContinuous: 20.0,
    ordibeheshtContinuous: 20.0,
    term2Continuous: 19.5,
    term2Final: 20.0,
    teacherName: 'استاد حسین حسینی',
  },
  {
    id: 'grd-101-4-2',
    studentId: 'stu-101-4',
    classId: 'cls-101',
    subjectId: 'sub-2',
    subjectName: 'فیزیک',
    coefficient: 3,
    mehrContinuous: 18.0,
    abanContinuous: 18.5,
    azarContinuous: 19.0,
    term1Continuous: 18.5,
    term1Final: 19.0,
    bahmanContinuous: 19.0,
    esfandContinuous: 19.0,
    farvardinContinuous: 19.5,
    ordibeheshtContinuous: 20.0,
    term2Continuous: 19.0,
    term2Final: 19.5,
    teacherName: 'استاد احمد رضایی',
  },

  // Student 5: دانیال رستمی (cls-101)
  {
    id: 'grd-101-5-1',
    studentId: 'stu-101-5',
    classId: 'cls-101',
    subjectId: 'sub-1',
    subjectName: 'ریاضی و حسابان',
    coefficient: 4,
    mehrContinuous: 20.0,
    abanContinuous: 20.0,
    azarContinuous: 20.0,
    term1Continuous: 20.0,
    term1Final: 20.0,
    bahmanContinuous: 20.0,
    esfandContinuous: 20.0,
    farvardinContinuous: 20.0,
    ordibeheshtContinuous: 20.0,
    term2Continuous: 20.0,
    term2Final: 20.0,
    teacherName: 'استاد حسین حسینی',
  },
  {
    id: 'grd-101-5-2',
    studentId: 'stu-101-5',
    classId: 'cls-101',
    subjectId: 'sub-2',
    subjectName: 'فیزیک',
    coefficient: 3,
    mehrContinuous: 19.5,
    abanContinuous: 19.5,
    azarContinuous: 20.0,
    term1Continuous: 19.5,
    term1Final: 20.0,
    bahmanContinuous: 20.0,
    esfandContinuous: 20.0,
    farvardinContinuous: 20.0,
    ordibeheshtContinuous: 20.0,
    term2Continuous: 20.0,
    term2Final: 20.0,
    teacherName: 'استاد احمد رضایی',
  },

  // Student from cls-102: پوریا ابراهیمی
  {
    id: 'grd-102-1-3',
    studentId: 'stu-102-1',
    classId: 'cls-102',
    subjectId: 'sub-3',
    subjectName: 'شیمی',
    coefficient: 3,
    mehrContinuous: 18.0,
    abanContinuous: 18.5,
    azarContinuous: 19.0,
    term1Continuous: 18.5,
    term1Final: 18.0,
    bahmanContinuous: 19.0,
    esfandContinuous: 19.0,
    farvardinContinuous: 19.5,
    ordibeheshtContinuous: 20.0,
    term2Continuous: 19.0,
    term2Final: 19.5,
    teacherName: 'استاد مریم کریمی',
  },
];

export const INITIAL_MORNING_DELAYS: MorningDelayRecord[] = [
  {
    id: 'md-1',
    studentId: 'stu-101-2', // علی‌رضا احمدی
    classId: 'cls-101',
    date: '1404/08/18',
    dayOfWeek: 'یکشنبه',
    arrivalTime: '07:50',
    delayMinutes: 20,
    reason: 'ترافیک و تاخیر سرویس',
    isExcused: true,
    recordedBy: 'استاد تقوی (معاون انضباطی)',
    disciplinaryActionTaken: 'ثبت و تذکر شفاهی',
    notes: 'ولی دانش‌آموز تلفنی ترافیک سنگین را تایید کرد.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'md-2',
    studentId: 'stu-101-2', // علی‌رضا احمدی
    classId: 'cls-101',
    date: '1404/08/20',
    dayOfWeek: 'سه‌شنبه',
    arrivalTime: '07:45',
    delayMinutes: 15,
    reason: 'خواب ماندن',
    isExcused: false,
    recordedBy: 'استاد تقوی (معاون انضباطی)',
    disciplinaryActionTaken: 'کسر ۰.۵ نمره انضباط',
    notes: 'دومین تاخیر در این هفته',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'md-3',
    studentId: 'stu-101-4', // متین صادقی
    classId: 'cls-101',
    date: '1404/08/12',
    dayOfWeek: 'دوشنبه',
    arrivalTime: '08:05',
    delayMinutes: 35,
    reason: 'کسالت و مراجعه به پزشک',
    isExcused: true,
    recordedBy: 'استاد تقوی (معاون انضباطی)',
    disciplinaryActionTaken: 'ثبت گواهی پزشک',
    notes: 'گواهی پزشک به دفتر تحویل داده شد.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'md-4',
    studentId: 'stu-101-4', // متین صادقی
    classId: 'cls-101',
    date: '1404/08/19',
    dayOfWeek: 'دوشنبه',
    arrivalTime: '07:55',
    delayMinutes: 25,
    reason: 'بدون عذر موجه',
    isExcused: false,
    recordedBy: 'استاد تقوی (معاون انضباطی)',
    disciplinaryActionTaken: 'ارسال پیامک به ولی',
    notes: 'تاخیر مکرر در روزهای دوشنبه',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'md-5',
    studentId: 'stu-102-2', // کیان حسینی
    classId: 'cls-102',
    date: '1404/08/17',
    dayOfWeek: 'شنبه',
    arrivalTime: '07:40',
    delayMinutes: 10,
    reason: 'مشکل وسیله نقلیه',
    isExcused: false,
    recordedBy: 'استاد تقوی (معاون انضباطی)',
    disciplinaryActionTaken: 'تذکر شفاهی',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'md-6',
    studentId: 'stu-201-1', // سهراب رحیمی
    classId: 'cls-201',
    date: '1404/08/15',
    dayOfWeek: 'پنج‌شنبه',
    arrivalTime: '08:00',
    delayMinutes: 30,
    reason: 'ترافیک ورودی اتوبان',
    isExcused: true,
    recordedBy: 'استاد تقوی (معاون انضباطی)',
    disciplinaryActionTaken: 'تایید موجه بودن',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'md-7',
    studentId: 'stu-301-2', // بردیا فراهانی
    classId: 'cls-301',
    date: '1404/08/19',
    dayOfWeek: 'دوشنبه',
    arrivalTime: '07:50',
    delayMinutes: 20,
    reason: 'خواب ماندن',
    isExcused: false,
    recordedBy: 'استاد تقوی (معاون انضباطی)',
    disciplinaryActionTaken: 'کسر ۰.۵ نمره انضباط',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_SCHOOL_ABSENCES: SchoolAbsenceRecord[] = [
  {
    id: 'abs-1',
    studentId: 'stu-101-3', // علیرضا شریفی
    classId: 'cls-101',
    date: '1404/08/18',
    dayOfWeek: 'یک‌شنبه',
    isExcused: false,
    reason: 'کسالت و عدم حضور در مدرسه بدون هماهنگی قبلی',
    recordedBy: 'استاد تقوی (معاون انضباطی)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'abs-2',
    studentId: 'stu-102-3', // محمد پارسا رضوی
    classId: 'cls-102',
    date: '1404/08/19',
    dayOfWeek: 'دوشنبه',
    isExcused: true,
    reason: 'مراجعه به پزشک و ارائه گواهی استعلاجی',
    recordedBy: 'استاد تقوی (معاون انضباطی)',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_OBSERVATIONS: StudentObservation[] = [
  {
    id: 'obs-1',
    studentId: 'stu-101-1', // علی محمدی
    date: '1404/08/18',
    time: '10:45',
    title: 'روحیه کار گروهی و راهنمایی همکلاسی‌ها در حل تمرین',
    category: 'social',
    categoryLabel: 'اجتماعی و ارتباطی',
    content: 'در زنگ تفریح و پس از کلاس هندسه، با سعه صدر به دو تن از دانش‌آموزان ضعیف‌تر کلاس تمرینات را توضیح می‌داد و بسیار صبور و خوش‌برخورد بود.',
    tags: ['همدلی', 'مسئولیت‌پذیری', 'کار تیمی'],
    location: 'کلاس ۱۰۱',
    recordedBy: 'حجت‌الاسلام رستمی (معاون تربیتی)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'obs-2',
    studentId: 'stu-101-1',
    date: '1404/08/10',
    time: '12:30',
    title: 'حضور داوطلبانه در اقامه نماز جماعت و نظم صفوف',
    category: 'moral',
    categoryLabel: 'اخلاقی و ارزشی',
    content: 'بدون نیاز به تذکر، در آماده‌سازی نمازخانه و چیدن مهرها کمک کرد و رفتار موقری در جمع دانش‌آموزان داشت.',
    tags: ['معنویت', 'نظم', 'داوطلبانه'],
    location: 'نمازخانه دبیرستان',
    recordedBy: 'حجت‌الاسلام رستمی (معاون تربیتی)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'obs-3',
    studentId: 'stu-101-2', // رضا رضایی
    date: '1404/08/19',
    time: '11:15',
    title: 'نشانه‌های اضطراب در هنگام پرسش کلاسی و امتحانات مستمر',
    category: 'emotional',
    categoryLabel: 'عاطفی و هیجانی',
    content: 'در زنگ فیزیک قبل از شروع کوییز دچار استرس و تعریق کف دست بود. نیاز به تمرین تن‌آرامی و تقویت باور به توانمندی‌های شخصی دارد.',
    tags: ['مدیریت اضطراب', 'اعتماد به نفس'],
    location: 'راهرو طبقه اول',
    recordedBy: 'حجت‌الاسلام رستمی (معاون تربیتی)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'obs-4',
    studentId: 'stu-101-3', // محمد حسینی
    date: '1404/08/16',
    time: '09:15',
    title: 'تمرکز بالا و اشتیاق به تفکر انتزاعی در مباحث فلسفی/دینی',
    category: 'learning_attitude',
    categoryLabel: 'نگرش و انگیزش تحصیلی',
    content: 'پرسش‌های عمیق هستی‌شناسانه و تمایل به مطالعه فراتر از کتب درسی نشان داد. ظرفیت بالایی برای پژوهش و کتابخوانی دارد.',
    tags: ['پرسشگری', 'استعداد تحلیلی'],
    location: 'کتابخانه مدرسه',
    recordedBy: 'حجت‌الاسلام رستمی (معاون تربیتی)',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_NURTURING_DOSSIERS: Record<string, StudentNurturingDossier> = {
  'stu-101-1': {
    studentId: 'stu-101-1', // علی محمدی
    thinkingPoints: [
      {
        id: 'tp-1',
        date: '1404/08/12',
        title: 'تفکر ساختارمند و اولویت‌بندی اهداف',
        content: 'دانش‌آموز دارای قدرت استدلال منطقی بسیار بالایی است. به چرایی مسائل اهمیت می‌دهد و مسائل را با دید علمی و فلسفی تحلیل می‌کند. به مفاهیم عدالت و اخلاق کاربردی گرایش زیادی دارد.',
        tags: ['منطق‌گرا', 'عدالت‌خواه'],
        keyTakeaways: ['تقویت کتابخوانی در حوزه منطق و تاریخ علم', 'تشویق به حضور در المپیادها'],
        createdAt: new Date().toISOString(),
      },
    ],
    privateSessions: [
      {
        id: 'ps-1',
        date: '1404/08/15',
        title: 'جلسه مشاوره فردی: مدیریت زمان و برنامه‌ریزی کنکوری',
        content: 'در این جلسه درباره تقسیم انرژی بین دروس تخصصی و عمومی گفت‌وگو شد. دانش‌آموز از کمال‌گرایی افراطی و نگرانی از عقب افتادن برنامه ابراز ناراحتی می‌کرد. تکنیک‌های پومودورو و اولویت‌بندی ماتریس آیزنهاور به وی آموزش داده شد.',
        tags: ['کمال‌گرایی', 'برنامه‌ریزی'],
        keyTakeaways: ['پذیرش خطاهای احتمالی', 'تثبیت خواب شبانه حداقل ۷ ساعت'],
        createdAt: new Date().toISOString(),
      },
    ],
    parentInterviews: [
      {
        id: 'pi-1',
        date: '1404/08/05',
        title: 'مصاحبه حضوری با پدر و مادر (آقای دکتر محمدی)',
        content: 'محیط خانواده بسیار فرهنگی و حامی است. والدین انتظارات منطقی دارند اما پدر به صورت ناخودآگاه استانداردهای بسیار بالایی برای نمرات تعیین می‌کند که موجب فشار روانی روی فرزند شده است. توافق شد بازخوردها بیشتر روی تلاش باشد تا صرفاً نمره ۲۰.',
        tags: ['انتظارات والدین', 'تعامل سازنده'],
        keyTakeaways: ['کاهش مقایسه با همسالان', 'اختصاص زمان تفریح خانوادگی در آخر هفته'],
        createdAt: new Date().toISOString(),
      },
    ],
    temperament: {
      dominantType: 'دموی - صفراوی',
      physicalTraits: 'قامت کشیده، چهره گندمگون روشن، نبض پر و حرارت بدنی معتدل متمایل به گرم',
      behavioralTraits: 'پرانرژی، برون‌گرا، پیشگام در فعالیت‌های جمعی، شجاع و صریح، گاهی کم‌طاقت در کارهای یکنواخت',
      entries: [
        {
          id: 'temp-1',
          date: '1404/07/25',
          title: 'بررسی اولیه طبایع و ویژگی‌های رفتاری',
          content: 'به دلیل غلبه طبع گرم و تر، استعداد یادگیری سریع دارد اما برای تمرکز طولانی‌مدت به تنوع و تغییر زاویه مطالعه نیاز دارد. پرهیز از ادویه‌جات تند و مصرف شربت سکنجبین و عناب توصیه شد.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    growthPath: [
      {
        id: 'gp-1',
        date: '1404/08/01',
        title: 'نقشه راه ترم اول: رشد مهارت حل تعارض و رهبری مثبت',
        content: 'هدف‌گذاری شده تا پایان نیمسال اول، مسئولیت هدایت حلقه علمی کلاس را بر عهده بگیرد و فن بیان و مدیریت هیجانات در گفت‌وگوهای چالشی را ارتقا دهد.',
        tags: ['رهبری تیم', 'فن بیان'],
        keyTakeaways: ['عضویت در شورای دانش‌آموزی', 'ارائه کنفرانس در مجمع عمومی'],
        createdAt: new Date().toISOString(),
      },
    ],
    lifestyle: [
      {
        id: 'ls-1',
        date: '1404/08/10',
        title: 'ارزیابی الگوی خواب، تغذیه و استفاده از گوشی همراه',
        content: 'میانگین خواب: ۲۳:۳۰ الی ۰۶:۱۵ (مناسب). استفاده از فضای مجازی روزانه حدود ۱.۵ ساعت که کنترل‌شده است. ورزش منظم شنا دو روز در هفته دارد. صبحانه کامل میل می‌کند.',
        tags: ['نظم فردی', 'ورزش مداوم'],
        createdAt: new Date().toISOString(),
      },
    ],
    interviews: [
      {
        id: 'int-1',
        date: '1404/07/15',
        title: 'مصاحبه ورودی سال تحصیلی جدید',
        content: 'در مصاحبه انگیزه بالایی برای قبولی در دانشگاه‌های برتر مهندسی نشان داد. علایق جانبی وی برنامه‌نویسی پایتون و نجوم است.',
        createdAt: new Date().toISOString(),
      },
    ],
    nurturingSummary: {
      overallSummary: 'علی دانش‌آموزی باهوش، مسئولیت‌پذیر، باوجدان و دارای ظرفیت‌های بالای مدیریتی است. چالش اصلی او کنترل کمال‌گرایی و مدارا با نوسانات مقطعی تحصیلی است. تعامل با مربیان بسیار محترمانه و سازنده است.',
      strengths: ['اخلاق‌مداری', 'اشتیاق به کمک به دیگران', 'تفکر منطقی و منسجم', 'نظم در تکالیف'],
      growthOpportunities: ['انعطاف‌پذیری در برابر ناملایمات', 'مهارت آرام‌سازی ذهنی در موقعیت‌های پرفشار'],
      entries: [
        {
          id: 'ns-1',
          date: '1404/08/18',
          title: 'جمعبندی تربیتی آبان‌ماه',
          content: 'روند رشد بسیار امیدبخش و رو به جلو است. خانواده همراهی عالی دارند و دانش‌آموز به خودآگاهی مطلوبی رسیده است.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    updatedAt: new Date().toISOString(),
  },
};

export const INITIAL_COACH_EVALUATIONS: CoachGrowthEvaluation[] = [
  {
    id: 'ce-1',
    studentId: 'std-101-1', // علی رضایی
    coachId: 'usr-coach-1',
    coachName: 'حجت‌الاسلام مهدی‌پور',
    date: '1404/08/15',
    period: 'فصل پاییز (آبان ۱۴۰۴)',
    criteria: {
      responsibility: 'excellent',
      teamwork: 'very_good',
      moralSpiritual: 'excellent',
      problemSolving: 'very_good',
      socialEtiquette: 'excellent',
      academicMotivation: 'very_good',
    },
    overallRating: 'excellent',
    strengths: [
      'پایبندی فوق‌العاده به نماز اول وقت و برنامه‌های معنوی',
      'خوش‌خلقی با هم‌کلاسی‌ها و روحیه امانت‌داری',
      'همکاری مؤثر در فعالیت‌های فرهنگی و مذهبی مدرسه'
    ],
    growthRecommendations: [
      'تقویت اعتماد به نفس در ارائه نظرات در مباحثات جمعی',
      'کاهش استرس و دغدغه‌های کمال‌گرایانه در آزمون‌ها'
    ],
    notes: 'جلسه بازخورد با حضور خود دانش‌آموز برگزار شد و اهداف رشد فردی تا دی‌ماه مشخص گردید.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ce-2',
    studentId: 'std-101-2', // محمد احمدی
    coachId: 'usr-coach-1',
    coachName: 'حجت‌الاسلام مهدی‌پور',
    date: '1404/08/18',
    period: 'فصل پاییز (آبان ۱۴۰۴)',
    criteria: {
      responsibility: 'very_good',
      teamwork: 'excellent',
      moralSpiritual: 'very_good',
      problemSolving: 'good',
      socialEtiquette: 'very_good',
      academicMotivation: 'good',
    },
    overallRating: 'very_good',
    strengths: [
      'توانایی بالا در ایجاد نشاط و انگیزه در جمع دوستان',
      'صداقت و روحیه گذشت در موقعیت‌های چالش‌برانگیز'
    ],
    growthRecommendations: [
      'برنامه‌ریزی منظم‌تر برای مطالعات روزانه',
      'تمرین مدیریت زمان و اولویت‌بندی در تکالیف'
    ],
    notes: 'پایش مستمر تکالیف و سبک زندگی با همکاری اولیا در حال پیگیری است.',
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_TEACHER_EVALUATIONS: TeacherEvaluation[] = [
  {
    id: 'te-1',
    teacherId: 'usr-tea-1', // استاد احمد رضایی (دبیر فیزیک)
    teacherName: 'استاد احمد رضایی',
    evaluatorId: 'usr-vp-edu-1',
    evaluatorName: 'مهندس کاظمی (معاونت آموزش)',
    date: '1404/08/20',
    period: 'ارزیابی جامع آبان‌ماه (فصل پاییز)',
    criteria: {
      lessonPlanning: 'excellent',
      punctuality: 'excellent',
      creativity: 'very_good',
      academicFollowUp: 'excellent',
      classroomManagement: 'very_good',
      studentSatisfaction: 'excellent',
    },
    overallRating: 'excellent',
    strengths: [
      'تدوین بودجه‌بندی دقیق و ارائه پیش‌نویس طرح درس قبل از آغاز ماه',
      'حضور همواره سر وقت قبل از نواخته شدن زنگ در کلاس',
      'ارائه آزمایش‌های کاربردی فیزیک و تشویق دانش‌آموزان به پروژه‌های عملی',
      'ثبت دقیق و به موقع تکالیف و نمرات مستمر در سامانه'
    ],
    growthRecommendations: [
      'استفاده بیشتر از پلتفرم‌های تعاملی و شبیه‌سازهای دیجیتال فیزیک',
      'برگزاری جلسات رفع اشکال انفرادی برای دانش‌آموزان دارای افت در مبحث ترمودینامیک'
    ],
    generalNotes: 'عملکرد آموزشی استاد رضایی در سطح الگو و بسیار شایسته تقدیر است. دانش‌آموزان کلاس‌های دهم و یازدهم رضایت حداکثری از شیوه تدریس ایشان دارند.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'te-2',
    teacherId: 'usr-tea-2', // استاد حسین حسینی (دبیر ریاضی)
    teacherName: 'استاد حسین حسینی',
    evaluatorId: 'usr-vp-edu-1',
    evaluatorName: 'مهندس کاظمی (معاونت آموزش)',
    date: '1404/08/22',
    period: 'ارزیابی جامع آبان‌ماه (فصل پاییز)',
    criteria: {
      lessonPlanning: 'very_good',
      punctuality: 'very_good',
      creativity: 'excellent',
      academicFollowUp: 'very_good',
      classroomManagement: 'excellent',
      studentSatisfaction: 'very_good',
    },
    overallRating: 'very_good',
    strengths: [
      'تسلط مثال‌زدنی بر مفاهیم حسابان و جبر پیشرفته',
      'قدرت بالا در برقراری سکوت پویا و مشارکت فعال همه دانش‌آموزان پای تخته',
      'طراحی سوالات مفهومی و مبتکرانه برای تمرین‌های هفتگی'
    ],
    growthRecommendations: [
      'ارائه بازخورد تشریحی بر روی تکالیف تحویلی دانش‌آموزان ضعیف‌تر',
      'تطبیق زمان‌بندی جلسات تدریس با بودجه‌بندی رسمی امتحانات نهایی'
    ],
    generalNotes: 'جلسه بازخورد با استاد حسینی با توافق بر سر ارتقای پایش انفرادی دانش‌آموزان نیازمند توجه برگزار شد.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'te-3',
    teacherId: 'usr-tea-3', // استاد مریم کریمی (دبیر شیمی)
    teacherName: 'استاد مریم کریمی',
    evaluatorId: 'usr-vp-edu-1',
    evaluatorName: 'مهندس کاظمی (معاونت آموزش)',
    date: '1404/08/25',
    period: 'ارزیابی جامع آبان‌ماه (فصل پاییز)',
    criteria: {
      lessonPlanning: 'very_good',
      punctuality: 'excellent',
      creativity: 'very_good',
      academicFollowUp: 'good',
      classroomManagement: 'very_good',
      studentSatisfaction: 'very_good',
    },
    overallRating: 'very_good',
    strengths: [
      'طراحی جزوات کمک‌آموزشی بسیار منظم با نمودارهای ساختار مولکولی',
      'نظم فوق‌العاده در ورود و خروج و رعایت دقیق سرفصل‌ها'
    ],
    growthRecommendations: [
      'پیگیری منظم‌تر تکالیف هفتگی و ثبت غیبت در تکالیف در سامانه مدرسه',
      'افزایش زمان پرسش کلاسی ابتدای هر زنگ'
    ],
    generalNotes: 'روند آموزشی مثبت است و هماهنگی‌های لازم با آزمایشگاه انجام گرفته است.',
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_SCHOOL_ANNOUNCEMENTS: SchoolAnnouncement[] = [
  {
    id: 'ann-1',
    title: 'دستورالعمل برگزاری آزمون‌های مستمر آبان و آذرماه ۱۴۰۴',
    content: 'همکاران گرامی و اساتید محترم؛ پیرو مصوبه شورای آموزشی مدرسه یاوران ولایت، بودجه‌بندی آزمون‌های میان‌ترم اول و ثبت نمرات مستمر تا تاریخ ۳۰ آذرماه در سامانه الزامی می‌باشد. لطفاً پیش‌نویس سوالات را حداقل یک هفته قبل به معاونت آموزش تحویل فرمایید.',
    date: '1404/08/20',
    category: 'educational',
    priority: 'urgent',
    targetRoles: ['teacher', 'vice_educational', 'admin'],
    authorName: 'مهندس کاظمی (معاونت آموزش)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ann-2',
    title: 'نشست هم‌اندیشی اساتید، مربیان یاوران ولایت و کادر تربیتی',
    content: 'نشست ماهانه بررسی روند تحصیلی-تربیتی دانش‌آموزان و هم‌افزایی معلمان و مربیان یاوران ولایت روز چهارشنبه ساعت ۱۴:۳۰ در سالن جلسات برگزار می‌گردد. حضور کلیه اساتید محترم مزید امتنان است.',
    date: '1404/08/18',
    category: 'general',
    priority: 'important',
    targetRoles: ['teacher', 'coach', 'vice_nurturing', 'vice_educational', 'vice_disciplinary', 'admin'],
    authorName: 'دکتر صادقی (مدیریت دبیرستان)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ann-3',
    title: 'کارگاه آموزشی: روش‌های نوین طراحی سوالات مفهومی و طرح درس هوشمند',
    content: 'معاونت آموزش با همکاری اساتید برتر، کارگاه دانش‌افزایی ویژه کادر تدریس با محوریت ارزشیابی کیفی و تلفیق فناوری در آموزش را در هفته آینده برگزار می‌نماید.',
    date: '1404/08/15',
    category: 'educational',
    priority: 'normal',
    targetRoles: ['teacher', 'vice_educational'],
    authorName: 'معاونت آموزش',
    createdAt: new Date().toISOString(),
  }
];


